### PR TITLE
`features list` command

### PR DESCRIPTION
**Pull request by TomasHofman**
Depends on https://github.com/wildfly-extras/prospero/pull/426

### CODE REVIEW

**Comment by spyrkob** [comment]
@TomasHofman are you still working on this?

**Comment by TomasHofman** [comment]
I think I forgot about this, I will get back to it.

**Comment by spyrkob** [comment]
@TomasHofman can I close this PR or are you planning on working on it?

**Comment by TomasHofman** [comment]
Yes, let's close it for now.

**Pull request closed without merging**
