### PR TITLE
[#726] Allow multiple manifests in the install command

### LINKED ISSUE #726: The `--manifest` parameter doesn't accept list of coordinates
The `--channel` parameter accepts list of coordinates, which is very practical. The `--manifest` parameter should support it too.

### PR DESCRIPTION
**Pull request by spyrkob**
Closes #726

### CODE REVIEW

**Comment by spyrkob** [comment]
@TomasHofman FYI

**Comment by TomasHofman** [comment]
Looks good! Is there any handling necessary in the `channel add` command, as you pointed out in the issue? Throwing error if there is more than one manifest defined..?

**Comment by spyrkob** [comment]
`channel add` operation should already only accept a single manifest (defined through the `@CommandLine.Option` annotations), that should not be affected by this changes, unless I missed something :)

**Comment by TomasHofman** [comment]
I see, it doesn't inherit from the AbstractInstallCommand. Sounds good :).

**Review by TomasHofman — APPROVED** [review]

**Comment by spyrkob** [comment]
Thanks for the review @TomasHofman :)

**Pull request merged**
