### PR TITLE
Use VersionMatcher.COMPARATOR to sort versions of the channel definition

### LINKED ISSUE #155: Prospero picks the wrong version of a GAV channel definition
Prospero picks up the "highest version" from a version range resolution result done by Maven.
https://github.com/wildfly-extras/prospero/blob/6d840a82a2e8554cbda9b582583d0b3078c01ac0/prospero-common/src/main/java/org/wildfly/prospero/wfchannel/ChannelRefUpdater.java#L87

This is inherently broken as Maven does not recognize a version scheme in those requests.
https://github.com/apache/maven/blob/e410a6ce1dea787258e5675e71a672144e3f0419/maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java#L134

So it picks up the first version in the list:
```
versions = {ArrayList@4425}  size = 7
 0 = {GenericVersion@4444} "1.0.0.Beta1-redhat-20220915"
 1 = {GenericVersion@4445} "1.0.0.Beta1-redhat-20220916"
 2 = {GenericVersion@4446} "1.0.0.Beta1-redhat-20220919"
 3 = {GenericVersion@4447} "1.0.0.Beta1-redhat-20220922"
 4 = {GenericVersion@4448} "1.0.0.Beta1-redhat-20220923"
 5 = {GenericVersion@4449} "1.0.0.Beta1-redhat-20220926"
 6 = {GenericVersion@4450} "1.0.0.Beta-redhat-00001"
```

### PR DESCRIPTION
**Pull request by wolfc**
Fixes #155

### CODE REVIEW

**Comment by wolfc** [comment]
@jmesnil this should probably be a function of [wildfly-channel](https://github.com/wildfly-extras/wildfly-channel).

**Comment by jmesnil** [comment]
The `maven-resolver` library of the wildfly-channel provides this feature https://github.com/wildfly-extras/wildfly-channel/blob/f39fd1dfee492b8645371b17555ef413b1ad2278/maven-resolver/src/main/java/org/wildfly/channel/maven/VersionResolverFactory.java#L177. Prospero should be able to leverage it.

**Comment by wolfc** [comment]
I was more looking at https://github.com/wildfly-extras/wildfly-channel/blob/269a382185a356f081cc3d4cd8d2efcebea64fa6/core/src/main/java/org/wildfly/channel/Channel.java#L184. A channel has the ability to hook up to required manifests via GA (or URL) but not its own manifest.

**Comment by spyrkob** [comment]
superseded by #159

**Pull request closed without merging**
