### PR TITLE
Mark and validate --provision-config and --channel as alternatives

### PR DESCRIPTION
**Pull request by TomasHofman**
Update usage message and throw an error when the two options are used together (currently --channel silently ignored).

Resolves https://github.com/wildfly-extras/prospero/issues/100

### CODE REVIEW

**Comment by spyrkob** [comment]
Should the same apply to `--remote-repositories` and `--provision-config`?

**Comment by TomasHofman** [comment]
OK. I will also try to put more detailed examples into the usage message.

**Comment by TomasHofman** [comment]
Screenshot from 2022-07-25 10-36-13

**Comment by TomasHofman** [comment]
Should `--channel` also support GAV?

**Comment by TomasHofman** [comment]
I find the examples are wrong, `prospero install --fpl=<GA-or-URL> --provision-config=<path> [OPTION]...` doesn't work.

Only these are valid:

```
prospero install --fpl=<predefined-name> [--channel=<URL> --remote-repositories=<URL>[,...]] [OPTION]...
prospero install --fpl=<GA-or-URL> --provision-config=<path> [OPTION]...
prospero install --definition=<path> [OPTION]...
```

**Comment by spyrkob** [comment]
> Should --channel also support GAV?
Yes, I think we can add GAV support

**Comment by TomasHofman** [comment]
Updated.

**Review by spyrkob — APPROVED** [review]

**Pull request merged**
