### PR TITLE
Move usage strings to a resource bundle, to allow localization

### LINKED ISSUE #33: Add help and syntax description
Add help operation listing available operations and their parameters.

Add --help argument to operations to display the operation's parameter

### PR DESCRIPTION
**Pull request by TomasHofman**
Fixes #33 
Part of #38

### CODE REVIEW

**Comment by TomasHofman** [comment]
Cc @spyrkob

**Comment by TomasHofman** [comment]
The install help screen now looks like this: Screenshot from 2022-06-23 14-49-07

**Comment by TomasHofman** [comment]
And the main command help:
Screenshot from 2022-06-24 09-11-19

**Comment by TomasHofman** [comment]
Translations to different languages can be created by adding a language specific property file to the resource bundle, e.g. adding UsageMessages_cs.properties for czech language or UsageMessages_de.properties for german.

For testing purposes, one can use the `-Duser.language=cs` argument to switch the language, as in:

```
java -Duser.language=cs -jar prospero-cli/target/prospero-cli-1.0-SNAPSHOT-shaded.jar
```

Two things remain to figure out for me:
* I don't yet know what determines the default language choice (it's not the LANG env variable).
* Native UTF characters like czech or polish characters with diacritic are not displayed correctly when the property file is UTF-8 encoded. Maybe the file needs to be ASCII encoded. Will test.

**Comment by spyrkob** [comment]
Looks great thanks!

**Comment by TomasHofman** [comment]
One update - native characters work when property files are UTF-8 encoded. My IDE was previously set to use ISO-8859 for property files, which was the problem.
Screenshot from 2022-06-24 09-37-57

**Comment by TomasHofman** [comment]
Update two: the default language choice *is* determined by LC_ALL or LANG env variables. E.g. both `LC_ALL=cs_CZ.UTF-8` and `LANG=cs_CZ.UTF-8` work, when there is given language property file in the resource bundle.

**Pull request merged**
